[package]
name = "burst"
version = "0.1.0"
authors = ["Joel Palmer <joel@joel.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_ec2 = "0.31.0"